### ISSUE TITLE
Openid login doesn't work

### ISSUE THREAD

**Issue by mkrl** [jsza/tempus-website#5]
After trying to sign up via Steam, you get redirected to the "User not authorized." page, the login itself doesn't seem to be working at all.

**Comment by jsza** [comment]
Hi, are you trying to log in on https://tempus.xyz/ or the client application running on Node? Currently, login is unsupported here. Eventually, the API backend will be available for it to connect to.

**Comment by mkrl** [comment]
I'm trying to log in on https://tempus.xyz/

**Comment by jsza** [comment]
Thank you. I think I've narrowed this down, can you try logging in again?

**Comment by mkrl** [comment]
I'm still getting the same error.

**Comment by jsza** [comment]
Right. Now it should be fixed.

**Comment by mkrl** [comment]
Now I'm getting 403 for the entire site after signing up. Can't really do anything unless the session expires.

**Comment by jsza** [comment]
Try again? Your session should be fixed as well if it's still active.

**Comment by mkrl** [comment]
Yep works well now, thanks.
